### ISSUE TITLE
Add some editor to the base image

### ISSUE THREAD

**Issue by jgomezdans** [jgomezdans/geog_docker#31]
My minimalist image is quickly loosing its purity... ;-)

I'll install levee, 40k vi-lookalike editor

UCL-EO/geog0111#2

**Comment by profLewis** [comment]
I'll never remember that in 6 months time ... can't I just have vi?? or at least can you put an alias in the user bashrc for this? minimalist isn't the main requirement here ... usability is ...

**Comment by jgomezdans** [comment]
It emulates (sorry) vi, just type vi and it should come up with something
that looks like vi.
