### ISSUE TITLE
Docker cache not cacheing

### ISSUE THREAD

**Issue by jgomezdans** [jgomezdans/geog_docker#6]
I spend good money on this cache thing but it seems it's not working... 
When (and if) it works, it should be used to push the image on release.

**Comment by jgomezdans** [comment]
This is mostly working now, so closing issue.

**Comment by profLewis** [comment]
Hi - I’m sure im just being stupid, but when I run the docker in Windows (at least) files created are not persistent.

It’s not a permissions thing as I can write.

Eg 

docker run jgomezdans/geog bash -c “echo hello > hello.dat; cat hello.dat”

-> hello

docker run jgomezdans/geog bash -c “cat hello.dat”

-> no such file or directory 

Is that the same on Linux? Must be a settings thing.

Lewis 

Professor Philip Lewis, UCL

**Comment by profLewis** [comment]
OK … so its not so hard .. use symbolic links everywhere. Heres my solution.

1. I think you mentioned one drive before & maybe we should indeed recommend that as the link. Ive assumed below. But its done by sym link again (!) so they could always change it...

2. Do we put that in the core Dockerfile?? If we leave the my_work, it is generic




3. They only need do the cmd.sh stuff once. Then 

docker run -v local:/volume -it -v "/Users/plewis/OneDrive - University College London":/local geog  

Which is getting a bit long … but that’s the fault of the dir name.
Lewis

**Comment by profLewis** [comment]
Or rather

docker run -p 8888:8888 -v local:/volume -it -v "/Users/plewis/OneDrive - University College London":/local geog

**Comment by profLewis** [comment]
Or maybe all of that symbolic link stuff is a red herring
And all you need do is:
https://phoenixnap.com/kb/docker-run-command-with-examples

For mounting volumes use the -vattribute with the specified location of the directory where you want to save the data, followed by where that data will be located inside the container.
-v [/host/volume/location]:[/container/storage]

Professor Philip Lewis, UCL
